Allow `Connection` to be interrupted
duckdb/duckdb-rs pull request #343
Opened 2024-06-20 02:30 UTC by rebasedming

Closes #342 

Allows the `Connection` to be interrupted, which is useful for cancelling long-running queries.

2024-06-20 03:18 UTC, Mause requested changes
Can we please get some tests and docs added? And remove the dsstore files

2024-06-20 13:59 UTC, rebasedming commented
> Can we please get some tests and docs added? And remove the dsstore files

Yep! Put this up hastily to see if there was appetite for this functionality. I can clean it up now and add tests if there is.

2024-07-10 07:31 UTC, Mytherin commented
Could you merge this with main, and perhaps also add some tests?

2024-07-12 21:02 UTC, rebasedming commented
Yes, I got distracted with other things the last few weeks. I'll finish up this PR.

2024-07-12 23:20 UTC, rebasedming commented
Hey @Mause @Mytherin, I could use your input on how you'd like to see this tested. What I'm envisioning is spawning a long-running query in one thread, and then interrupting the same connection from another thread. Unfortunately, once a `Connection` is moved to a thread, it can't really be called from another thread. For instance, the following code won't compile because `db` is moved to the thread and you can't call `interrupt` on it afterward.

```rust
  #[test]
  fn test_interrupt() -> Result<()> {
      let db = checked_memory_handle();

      let query_handle = std::thread::spawn(move || {
          let mut stmt = db.prepare("CREATE TABLE foo AS SELECT generate_series(1, 10000000) AS id;")?;
          stmt.execute([])?;
          Ok(())
      });

      // Wait for the query to start
      std::thread::sleep(std::time::Duration::from_millis(1000));
      db.interrupt();

      let query_result: Result<(), Error> = query_handle.join().unwrap();
      assert!(query_result.is_err());
      Ok(())
  }
```

2024-07-13 11:24 UTC, Mytherin commented
That idea for a test sounds good to me. 

> Unfortunately, once a Connection is moved to a thread, it can't really be called from another thread. For instance, the following code won't compile because db is moved to the thread and you can't call interrupt on it afterward.

I'm not too familiar with Rust specifics - but how do you envision this method to be used in practice if this is not possible? Maybe there needs to be some annotation that signifies it is safe to call `interrupt` from a different thread?

2024-07-13 16:18 UTC, rebasedming commented
> That idea for a test sounds good to me.
> 
> > Unfortunately, once a Connection is moved to a thread, it can't really be called from another thread. For instance, the following code won't compile because db is moved to the thread and you can't call interrupt on it afterward.
> 
> I'm not too familiar with Rust specifics - but how do you envision this method to be used in practice if this is not possible? Maybe there needs to be some annotation that signifies it is safe to call `interrupt` from a different thread?

In practice, I've stored the `Connection` in a [static global](https://github.com/paradedb/paradedb/blob/079350071a1280cddcf10fa1359ce63fcc704c5b/pg_lakehouse/src/duckdb/connection.rs#L35). I do the same for the tests if you're comfortable with it?

2024-07-15 13:03 UTC, Mytherin commented
If the tests are completely stand-alone I don't mind - but ideally we don't ship any static globals. Is there no other way?

2025-07-02 13:58 UTC, mlafeldt commented
Superseded by #493

2025-07-02 13:58 UTC, closed without merging